GET http://localhost:5000/api/members

###

POST http://localhost:5000/api/members
Content-Type: application/json

{
    "name": "Bob Smith",
    "email": "jake@gmail.com"
}

###

get http://localhost:5000/api/members/1

###
put http://localhost:5000/api/members/1
Content-Type: application/json

{
    "email": "john@yahoo.com"
}